name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  # Build project & Unit tests
  simple_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Check style
        run: npm run eslint

      - name: Run build
        run: npm run build

      - name: Run unit tests
        run: npm run test

  # E2E - paralel to unit tests
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5

  # Deplyo to Fly.io 
  # Waits for both unit and E2E tests to complete
  deploy_to_fly:
    needs: [simple_pipeline, e2e_tests]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  # Tag versioning on successful deploy
  tag_release:
    needs: [deploy_to_fly]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  # Discord success notification
  notify_success:
    needs: [deploy_to_fly]
    runs-on: ubuntu-latest
    steps:
      - name: Discord Success Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: "Success"
          title: 'Deployment Successful! A new version deployed to production'
          nodetail: true
          color: '0x2ecc71'
          description: |
            **Deployment Details**

            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.actor }}

  # Discord failure notification
  notify_failure:
    needs: [simple_pipeline, e2e_tests, deploy_to_fly]
    if: ${{ failure() }} 
    runs-on: ubuntu-latest
    steps:
      - name: Discord Failure Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: "Failure"
          title: 'Build Failed! The pipeline encountered an error'
          nodetail: false
          color: '0xe74c3c'
